site_name: Solcast API C# SDK
site_url: https://solcast.github.io/solcast_net/
site_dir: public
theme:
  name: material
  logo: 'img/logo.png'
  palette:
    primary: black
    accent: yellow
  features:
    - content.tooltips

nav:
  - Home: index.md
  - Forecast: forecast.md
  - Live: live.md
  - Historic: historic.md
  - TMY: tmy.md
  - PV Power Site: pvpowersite.md
  - Aggregation: aggregation.md
  - Example Notebooks:
    - '1. Getting Data':
      - '1.1 Getting Data: Historic Solar Radiation': 'notebooks/1.1 Getting Data - Historic Solar Radiation.ipynb'

extra:
  alternate:
    - name: Python
      link: https://solcast.github.io/solcast-api-python-sdk/
      lang: python
    - name: C#
      link: /solcast_net/
      lang: csharp

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - abbr
  - attr_list

plugins:
  - mkdocs-jupyter
#   - mkdocstrings:
#       enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
#       default_handler: python
#       handlers:
#         python:
#           options:
#             show_source: false
